services:
  tinyauth:
    container_name: tinyauth
    image: tinyauth-custom:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    env_file: .env

networks:
  proxy:
    external: true